---
title: "GTEx aging gene"
output: html_document
date: "2023-07-18"
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(tidyverse)
library(BiocParallel)
library(reshape2)
library(grid)
library(ggsignif)
library(patchwork)
rm(list = ls())
setwd("/path/to/GTEx/data/folder/") 
```

# senescence genelists
```{r}
library(ReactomeContentService4R)
library(KEGGREST)
library(cmapR)
senmayo = readxl::read_excel("./SnGs/senmayo.xlsx")
senmayo = str_to_upper(senmayo$`Gene(human)`)

genAge = read_csv("./SnGs/genage_human.csv")
genAge = str_to_upper(genAge$symbol)

cellAge = readr::read_tsv("./SnGs/cellage3.tsv")
cellAge.d = cellAge$`Senescence Effect`
cellAge.d[cellAge.d == "Unclear"] = NA
cellAge.d[cellAge.d == "Induces"] = "up"
cellAge.d[cellAge.d == "Inhibits"] = "down"
cellAge = str_to_upper(cellAge$`Gene symbol`)

csgene = read.delim("./SnGs/csgene_human.txt")
csgene = str_to_upper(csgene$GeneSymb)

go = parse_gmt("./SnGs/GOBP_CELLULAR_SENESCENCE.v2023.2.Hs.gmt")[[1]]$entry
go.up = parse_gmt("./SnGs/GOBP_POSITIVE_REGULATION_OF_CELLULAR_SENESCENCE.v2023.2.Hs.gmt")[[1]]$entry
go.down = parse_gmt("./SnGs/GOBP_NEGATIVE_REGULATION_OF_CELLULAR_SENESCENCE.v2023.2.Hs.gmt")[[1]]$entry
go.d = rep(NA, length(go)); names(go.d) = go
go.d[go.up] = "up"; go.d[go.down] = "down"

# KEGG cellular senescence
pathway <- keggGet("hsa04218")[[1]]
kegg <- pathway$GENE
kegg = kegg[seq(2,312,2)]
kegg = sub(";.*", "", kegg)
# Reactome
reac = event2Ids(event.id = "R-HSA-2559583")
reac = reac$geneSymbol
# sasp
sasp = event2Ids(event.id = "R-HSA-2559582")
sasp = sasp$geneSymbol
# senequest
quest = as.data.frame(read_csv("./SnGs/seneQuest.csv"))
rownames(quest) = quest$`Gene symbol`
quest = quest[quest$n_literature >= 15 & quest$percentage >= 0.8, ]
quest.d = quest$up_down
quest = rownames(quest)

all.genes = unique(c(senmayo, genAge, cellAge, csgene, kegg, reac, go, sasp, quest))
results = data.frame(
  Senmayo = all.genes %in% senmayo,
  geneAge = all.genes %in% genAge,
  cellAge = all.genes %in% cellAge,
  CSgene = all.genes %in% csgene,
  GO = all.genes %in% go,
  KeggCS = all.genes %in% kegg,
  ReacCS = all.genes %in% reac,
  ReacSASP = all.genes %in% sasp,
  Quest = all.genes %in% quest
)
rownames(results) = all.genes

results$n = rowSums(results)

# get direction
results$go.d = NA; results$cellAge.d = NA; results$quest.d = NA
results[go, "go.d"] = go.d
results[quest, "quest.d"] = quest.d
results[cellAge, "cellAge.d"] = cellAge.d


# database agreement
results$percent = rowMeans(results[,c("go.d", "cellAge.d", "quest.d")] == "up", na.rm = T)
results$direction = NA
for (i in 1:nrow(results)) {
  if (is.na(results$percent[i])) {results$direction[i] = NA}
  else if (results$percent[i] == 1) {results$direction[i] = "up"}
  else if(results$percent[i] == 0) {results$direction[i] = "down"}
}
saveRDS(results, "./SnGs.rds")
```

# get matrix
```{r}
out = readRDS("./bulk_dge.rds")
# tissues with <100 samples
bad.t = c("Cervix_Uteri", "Fallopian_Tube", "Bladder")
out = out[!names(out) %in% bad.t]
tissues = names(out)
sign.mtx = NULL
logFC.mtx = NULL
sig.mtx = NULL

for (t in tissues) {
  tab = out[[t]]
  logFC = tab$logFC
  logFC.mtx = cbind(logFC.mtx, logFC)
  sign = ifelse(tab$logFC > 0, 1, -1)
  sign.mtx = cbind(sign.mtx, sign)
  sig = ifelse(tab$adj.P.Val<0.05, "sig", "non-sig")
  sig.mtx = cbind(sig.mtx, sig)
}

process = function(mtx) {
  rownames(mtx) = rownames(out[[1]])
  colnames(mtx) = tissues
  return(mtx)
}
sign.mtx = process(sign.mtx)
logFC.mtx = process(logFC.mtx)
sig.mtx = process(sig.mtx)
```

# Fig1
1a
```{r}
library(ggpubr)
df1a = data.frame(
  geneset = rev(c("cellAge", "quest", "go", "csgene", "reac", "genAge", "kegg", "sasp", "senmayo")),
  "n_genes" = rev(c(length(cellAge), length(quest), length(go), length(csgene), length(reac), length(genAge), length(kegg), length(sasp), length(senmayo)))
)
df1a = df1a %>% arrange(n_genes)
f1a0 = ggplot(df1a, aes(x = geneset, y=n_genes, fill=geneset)) + 
  geom_bar(stat="identity", alpha = 0.6, color="black") +
  scale_fill_brewer(palette = "Paired") +
  scale_x_discrete(limits = rev(df1a$geneset)) +
  labs(x = NULL, y="number of genes") +
  geom_text(aes(label = signif(n_genes)), nudge_y = rep(20,9))  +
  theme_minimal()
f1a0
```

1b
```{r}
jaccard <- function(list1, list2) {
  intersection <- length(intersect(list1, list2))
  union <- length(union(list1, list2))
  if (union == 0) {
    return(0)  # This handles the edge case where both sets are empty.
  } else {
    return(intersection / union)
  }
}
geneLists <- list(senmayo, genAge, cellAge, csgene, kegg, reac, go, sasp, quest)
numLists <- length(geneLists)

# Initialize an empty matrix
jaccardMatrix <- matrix(0, nrow=numLists, ncol=numLists)

# Fill the matrix
for (i in 1:numLists) {
  for (j in 1:numLists) {
    jaccardMatrix[i, j] <- jaccard(geneLists[[i]], geneLists[[j]])
  }
}

# Name the rows and columns for clarity
rownames(jaccardMatrix) <- colnames(jaccardMatrix) <- c("SenMayo", "genAge", "cellAge", "CSgene", "KEGG:cs", "REAC:cs", "GO:cs", "SASP", "Quest")
order = c("cellAge", "Quest", "GO:cs", "CSgene", "REAC:cs", "genAge", "KEGG:cs", "SASP", "SenMayo")

library(paletteer)

jaccardMatrix = melt(jaccardMatrix)
jaccardMatrix$Var1 = factor(jaccardMatrix$Var1, levels = order)
jaccardMatrix$Var2 = factor(jaccardMatrix$Var2, levels = order) 

d <- jaccardMatrix
d <- cbind(d,text=round(d[,3],2))
d[d[,1]==d[,2],3] <- NA
library(ggplot2)
f1b = ggplot(d,aes(x=Var1,y=Var2,fill=value,label=text)) + geom_tile() + geom_text(size=6.5) + theme_classic() + scale_fill_gradient2(low='white',high='red',mid='orange',midpoint=0.3,na.value = 'grey90') + labs(fill = NULL) + theme_void() + guides(fill="none")
f1b
```

1c
```{r}
library(ggforce)
library(ggrepel)
library(RColorBrewer)
pie <- data.frame(
  state = c(as.character(1:4), ">=5"),
  amount = c(as.vector(table(results$n))[1:4], 44),
  focus = c(0, 0, 0, 0, 0.4),
  r0 = rep(0, 5)
)
pie$state = factor(pie$state, levels = c(as.character(1:4), ">=5"))

fun=function(x) {paste0(x[2], " genes in\n", x[1], " gene sets")}
labels=apply(pie, MARGIN = 1, fun)

x = c(0.48, -0.53, -1, -0.55, 0.4)
y = c(-0.1, 0, 0.9, 1.24, 1.3)

f1c = ggplot(pie) +
  geom_arc_bar(aes(x0 = 0, y0 = 0, r0 = r0, r = 1, amount = amount, fill = state, explode = focus), data = pie, stat = 'pie') +
  coord_fixed() +
  geom_text(aes(label = labels, x = x, y = y), size = 4.1) +
  scale_fill_brewer(palette = "PuBu", type = 'qual') +
  geom_segment(aes(x=-0.19, y=0.88, xend=-0.3, yend=1.08)) +
  geom_segment(aes(x=-0.06, y=1.15, xend=0.05, yend=1.3)) +
  geom_segment(aes(x=-0.7, y= 0.85, xend =-0.4, yend = 0.65)) +
  xlim(-1.5, 1.5) +
  theme_void() +
  theme(legend.position="none")
f1c
```

1e
```{r}
g = rownames(results)[results$n >= 5]
row_clu5 = hclust(dist(logFC.mtx[rownames(results)[results$n == 5],]))
row_clu6 = hclust(dist(logFC.mtx[rownames(results)[results$n == 6],]))
col_clu = hclust(dist(t(logFC.mtx[g,])))

# to data.frame
data = data.frame(
  genes = rep(rownames(logFC.mtx[g,]), dim(logFC.mtx[g,])[2]),
  tissues = rep(colnames(logFC.mtx[g,]), each=dim(logFC.mtx[g,])[1]),
  logFC = abs(as.vector(logFC.mtx[g,])),
  sign = as.vector(sign.mtx[g,]),
  significance = as.vector(sig.mtx[g,])
)
data$genes = factor(data$genes, levels = c(c("CDKN2B", "IL6", "CDKN2A", "CDKN1A"), rownames(results)[results$n ==7], rev(row_clu6$labels), rev(row_clu5$labels)))
data$tissues = factor(data$tissues, levels = col_clu$labels)
data$n_gs = plyr::mapvalues(data$genes, rownames(results), results$n, warn_missing = F)
data$n_gs = paste0("reported in\n ", data$n_gs, " gene sets")
data$n_gs = factor(data$n_gs, levels = paste0("reported in\n ", 8:5, " gene sets"))
data$sign = as.factor(ifelse(data$sign == "1", "positive", "negative"))
data = na.omit(data)
data$tissues = sub("_", " ", data$tissues)
data$tissues[data$tissues == "Adipose Tissue"] = "Adipose"
data$significance = ifelse(data$significance == "sig", "significant", "non significant")
f1e = ggplot(data, aes(x = tissues, y = genes, fill = significance, size = logFC, color = sign)) +
  geom_point(aes(alpha = significance), stroke=0) +
  facet_grid(n_gs~., scales="free", space="free") +
  scale_size_continuous(range = c(2,5)) +
  scale_alpha_manual(values = c(0.5, 1), na.value = NA) +
  scale_fill_manual(values = c("#237DFD", "#FB5225"), na.value = NA) +
  scale_color_manual(values = c("negative" = "#237DFD", "positive" = "#FB5225")) +
  theme(
    panel.background = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_rect(fill = NA, color = "black"),
    strip.text.y = element_text(angle = 0),
    strip.background = element_blank(),
    axis.text.x = element_text(angle = 50, hjust = 1),
    legend.position = "bottom",
    legend.spacing.x = unit(0.1, "cm"),
    legend.box = "horizontal",
    legend.box.margin = margin(-10, -10, -10, -10),
    legend.key = element_blank(),
    
  ) +
  guides(alpha = guide_legend(nrow = 2,order=1, label.position = "right", override.aes = list(size = 2.3)),
         color = guide_legend(nrow = 2, order=2, label.position = "right",override.aes = list(size = 2.3)),
         size = guide_legend(order=3, label.position = "top"),
         fill = "none") +
  labs(x = NULL, y = NULL, color = "Age-association", size = "Log2 fold change", fill=NULL, alpha="Significance", title="Age association")
f1e
```

1d
```{r}
# gene occurance summary
fun = function(x){ifelse(x, 1, 0)}
o = t(apply(as.matrix(results[,1:9]), MARGIN = 1, fun))
o1 = o[c(rownames(results)[results$n == 8], rownames(results)[results$n == 7],rownames(results)[results$n == 6], rownames(results)[results$n == 5]), ]

o1 = melt(o1)
colnames(o1) = c("gene", "geneset", "present")
o1$present = as.character(o1$present)
o1$n_genesets = plyr::mapvalues(o1$gene, rownames(results), results$n, warn_missing = F)
o1$n_genesets = paste0("reported in\n ", o1$n_genesets, " gene sets")
o1$n_genesets = factor(o1$n_genesets, levels = paste0("reported in\n ", as.character(8:5), " gene sets"))
o1$gene = factor(o1$gene, levels = levels(data$genes))


o1$GO = plyr::mapvalues(o1$gene, rownames(results), results$go.d, warn_missing = F)
o1$cellAge = plyr::mapvalues(o1$gene, rownames(results), results$cellAge.d, warn_missing = F)
o1$quest = plyr::mapvalues(o1$gene, rownames(results), results$quest.d, warn_missing = F)

o1$direction = NA
o1$direction[o1$geneset == "GO" & o1$GO == "up"] = "Inducing senescence"
o1$direction[o1$geneset == "cellAge" & o1$cellAge == "up"] = "Inducing senescence"
o1$direction[o1$geneset == "Quest" & o1$quest == "up"] = "Inducing senescence"
o1$direction[o1$geneset == "GO" & o1$GO == "down"] = "Inhibiting senescence"
o1$direction[o1$geneset == "cellAge" & o1$cellAge == "down"] = "Inhibiting senescence"
o1$direction[o1$geneset == "Quest" & o1$quest == "down"] = "Inhibiting senescence"
o1$direction[is.na(o1$direction)] = "direction not reported"


o1$geneset = factor(o1$geneset, levels = c("cellAge", "Quest","GO", "CSgene", "ReacCS", "geneAge", "KeggCS", "ReacSASP", "Senmayo"))
o1$shape = paste0(o1$present, o1$direction)
o1$shape[o1$shape == "1Inducing senescence"] = "Inducing senescence"
o1$shape[o1$shape == "1Inhibiting senescence"] = "Inhibiting senescence"
o1$direction = factor(o1$direction, levels = c("Inducing senescence", "Inhibiting senescence", "direction not reported"))
f1d= ggplot(o1) +
  geom_tile(data = o1, aes(x = geneset, y = gene), color = "#5B5C5B", size = 0.3, alpha = 0.2, fill="white") +
  geom_point(data = o1, size=0.8, aes(x=geneset, y=gene, shape = shape, color = direction, fill=direction), stroke = 1) +
  scale_shape_manual(values = c("0direction not clear" = 30, "1direction not reported" = 15, "Inducing senescence" = 24, "Inhibiting senescence" = 25)) +
  scale_fill_manual(values = c("0direction not clear" = "white", "1direction not reported" = "white", "Inducing senescence" = "red", "Inhibiting senescence" = "blue")) +
  scale_color_manual(values = c("Inhibiting senescence" = "blue", "Inducing senescence" = "red", "direction not reported" = "#424242")) +
  facet_grid(n_genesets ~ ., scales="free", space="free") +
  labs (x = NULL, y = NULL, color=NULL, title = "Senescence direction") +
  guides(shape = "none", fill="none") + 
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major =element_blank(),
    panel.grid.minor = element_line(color = "black"),
    axis.ticks = element_blank(),
    strip.text.y = element_text(angle = 0),
    strip.background = element_rect(fill = "white"),
    legend.position = "bottom",
    axis.text.x = element_blank(),
    legend.key = element_blank(),
    plot.title = element_text(size = 12)
  )
f1d

```

# Fig2 
metrics
```{r}
ctrl.genes = rownames(sign.mtx)[!rownames(sign.mtx) %in% rownames(results)]
control = as.data.frame(matrix(F, nrow = length(ctrl.genes), ncol = 9))
control = cbind(control, 0)
rownames(control) = ctrl.genes
colnames(control) = colnames(results)[1:10]
results.all = rbind(results[,1:10], control)


get_percent = function(sign.mtx, sig.mtx, results.all) {
  gene = intersect(rownames(results.all), rownames(sign.mtx))
  sn = sign.mtx[gene,]
  sg = sig.mtx[gene,]
  fun.sn = function(x) {
    if(sum(!is.na(x)) < 10) {
      return (NA)
    } else {
      x = x[!is.na(x)]
      return(max(sum(x>0), sum(x<0))/length(x))
    }
  }
  fun.sg = function(x) {
    if(sum(!is.na(x)) < 10) {
      return (NA)
    } else {
      x = x[!is.na(x)]
      return(sum(x == "sig")/length(x))
    }
  }
  signs = apply(sn, 1, fun.sn)
  sigs = apply(sg, 1, fun.sg)
  
  r12 = data.frame(n = results.all[,"n"])
  rownames(r12) = rownames(results.all)
  r12$sign = NA; r12$sig = NA
  r12[names(signs), "sign"] = signs
  r12[names(sigs), "sig"] = sigs
  return(r12)
}

r12 = get_percent(sign.mtx, sig.mtx, results.all)
signs = NULL; sigs = NULL; n_genesets = NULL
for (i in 1:8) {
  signs = c(signs, r12$sign[r12$n >= i])
  sigs = c(sigs, r12$sig[r12$n >= i])
  n_genesets = c(n_genesets, rep(paste0(">=",i), sum(r12$n >= i)))
}
df12 = data.frame(n_genesets = n_genesets, sign = signs, sig = sigs)
ctrl = r12[r12$n == 0,]; colnames(ctrl)[1] = "n_genesets"
df12 = rbind(df12, ctrl)
df12$n_genesets = factor(df12$n_genesets, levels = c("0", paste0(">=", 1:8)))
df12 = na.omit(df12)
```

2a
```{r}
f2h1 = ggplot(df12, aes(x = n_genesets, y=sign, fill = n_genesets)) +
  geom_violin(alpha = 0.5, adjust = 1.5) +
  stat_summary(fun = mean, geom = "point", size = 2, color = "black") +
  stat_summary(fun=mean, geom="line", aes(group=1), color="#3E3C3C")+
  geom_signif(comparisons = list(c(">=8", "0"), c(">=7", "0"), c(">=6", "0")), map_signif_level=TRUE, test = "wilcox.test", y_position = c(1.08, 1.04, 1)) +
  scale_fill_brewer(palette = "PuBu") +
  labs(x = NULL, y = NULL, fill = "n genesets") +
  theme_bw() +
  ggtitle("Sign agreement (GTEx)")
f2h1
```

2b
```{r}
f2h2 = ggplot(df12, aes(x = n_genesets, y=sig, fill = n_genesets)) +
  geom_violin(alpha= 0.5, adjust=4) + 
  stat_summary(fun = mean, geom = "point", size = 2, color = "black") +
  stat_summary(fun=mean, geom="line", aes(group=1), color="#3E3C3C")+
  geom_signif(comparisons = list(c(">=8", "0"), c(">=7", "0"), c(">=6", "0")), map_signif_level=TRUE, test = "wilcox.test", y_position = c(1.04, 0.98, 0.92)) +
  scale_fill_brewer(palette = "BuPu") +
  labs(x = NULL, y = NULL, fill = "n genesets") +
  theme_bw() +
  ggtitle("Significance percent (GTEx)")
f2h2
```


2c
```{r}
g = intersect(rownames(results), rownames(sign.mtx))
fun = function(x){mean(x == 1, na.rm=T)}
bulk_percent = apply(sign.mtx[g,],1,fun)
results$bulk_percent = NA
results[g, "bulk_percent"] = bulk_percent

r5 = results[!is.na(results$percent),]
r5 = r5[r5$percent == 1 | r5$percent == 0,]
r5 = r5[!is.na(r5$bulk_percent),]
a = NULL
for (i in 1:nrow(r5)) {
  if (r5[i, "direction"] == "up") {
    a = c(a, r5[i, "bulk_percent"])
  } else {
    a = c(a, 1-r5[i, "bulk_percent"])
  }
}
r5$a = a
a1 = r5$a[r5$n ==1]
a2 = r5$a[r5$n >=2]
a3 = r5$a[r5$n >=3]
a4 = r5$a[r5$n >=4]
a5 = r5$a[r5$n >=5]
a6 = r5$a[r5$n >=6]
a7 = r5$a[r5$n >=7]
a8 = r5$a[r5$n >=8]
df3 = data.frame(
  n_gs = rep(c("=1", paste0(">=", 2:8)), c(length(a1), length(a2),length(a3), length(a4), length(a5), length(a6), length(a7), length(a8))),
  as = c(a1,a2,a3,a4,a5,a6,a7,a8)
)
f2h3 = ggplot(df3, aes(x = n_gs, y = as, fill = n_gs)) + 
  geom_violin(alpha = 0.6, adjust=1.5) + 
  stat_summary(fun = mean, geom = "point", size = 2, color = "black") +
  stat_summary(fun=mean, geom="line", aes(group=1), color="#3E3C3C")+
  geom_signif(comparisons = list(c(">=8", "=1"), c(">=7", "=1"), c(">=6", "=1")), map_signif_level=TRUE, test = "wilcox.test", y_position = c(1.12, 1.06, 1)) +
  scale_fill_brewer(palette = "RdPu") +
  labs(x = NULL, y = NULL, fill="n genesets") +
  theme_bw() + 
  ggtitle("Annotation agreement (GTEx)")
f2h3
```


2d
```{r}
p8 = 5/1; p7 = 17/4; p6=146/50; p5=569/196; p4=1668/597; 
p3=7073/2861; p2=22286/9927; p1=67491/39720
df4 = data.frame(n_gs = paste0(">=",1:8), ps = c(p1,p2,p3,p4,p5,p6,p7,p8))
f2h4 = ggplot(df4, aes(x=n_gs, y=ps, fill=n_gs)) +
  geom_bar(stat = "identity", alpha=0.6, color="black") +
  scale_fill_brewer(palette = "YlOrRd") +
  theme_bw() +
  labs(x = NULL, y = "n_edge/n_expected", fill="n genesets") +
  ggtitle("PPI enrichment (human)")
f2h4
```
